package handlers

import (
	"bytes"
	"fmt"
	stdhtml "html"
	"html/template"
	"io"
	"net/url"
	"regexp"
	"strconv"
	"strings"

	"dolmen/models"
	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"
	emoji "github.com/yuin/goldmark-emoji"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer"
	htmlrenderer "github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
	"gopkg.in/yaml.v3"
)

// fileRenderer turns one gist file into display HTML: rendered markdown for
// *.md, syntax-highlighted code (by file name or fence language) for anything
// chroma recognizes, and an escaped <pre> otherwise. MathJax-delimited math
// and mermaid fences are detected so the template loads only the vendored JS
// the page actually needs.
type fileRenderer struct {
	policy    *bluemonday.Policy
	highlight *chromahtml.Formatter // no line numbers (markdown fences)
	numbered  *chromahtml.Formatter // line numbers (standalone code files)
	style     *chroma.Style
}

// FileRender is one file rendered for display. Body is self-contained block
// markup: rendered markdown or a code chroma/`<pre>` block.
type FileRender struct {
	Name         string
	Body         template.HTML
	NeedsMath    bool
	NeedsMermaid bool
	// Kind drives presentation: "text" renders Body; image/audio/video/pdf
	// embed RawURL; "file" is a download-only blob.
	Kind     string
	RawURL   template.URL
	SizeText string
}

// rawURL builds the app URL for a file; blobs answer with a redirect to S3.
func rawURL(gistID, name string) string {
	return "/raw/" + gistID + "/" + url.PathEscape(name)
}

func newFileRenderer() *fileRenderer {
	return &fileRenderer{
		policy:    displayPolicy(),
		highlight: chromahtml.New(chromahtml.WithClasses(true)),
		numbered:  chromahtml.New(chromahtml.WithClasses(true), chromahtml.WithLineNumbers(true)),
		style:     styles.Get("github"),
	}
}

// displayPolicy renders gist content safely. Chroma emits class-named
// spans/tables and mermaid fences need a class; UGC strips class by default,
// so allow it back — no user-controlled CSS is ever served, classes only
// map to the fixed stylesheets we ship.
func displayPolicy() *bluemonday.Policy {
	p := bluemonday.UGCPolicy()
	p.AllowElements("table", "thead", "tbody", "tr", "td", "th", "div", "span")
	p.AllowAttrs("class").Globally()
	// Task-list checkboxes only: goldmark's TaskList emits disabled inputs,
	// which the UGC forms ban would otherwise strip.
	p.AllowAttrs("type").Matching(checkboxType).OnElements("input")
	p.AllowAttrs("checked", "disabled").OnElements("input")
	// ids are generated by goldmark (heading slugs, footnote fn:/fnref:
	// links), never taken verbatim from user text; the charset regex keeps
	// raw-HTML-injected ids out of DOM-clobbering shapes. Note: UGC's
	// AllowStandardAttributes already admits id/title globally with their
	// own charset-limited regexes and bluemonday offers no removal API,
	// so raw HTML can still set those two — accepted: the charset bounds
	// the effect to id collisions, not script or markup injection.
	p.AllowAttrs("id").Matching(safeID).OnElements("h1", "h2", "h3", "h4", "h5", "h6", "sup", "li", "div")
	// The one gap in UGC vs GitHub's raw-HTML subset.
	p.AllowElements("kbd")
	return p
}

var (
	checkboxType = regexp.MustCompile(`^checkbox$`)
	safeID       = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9:._-]{0,63}$`)
)

func (fr *fileRenderer) Render(name, content string) FileRender {
	if models.IsMarkdown(name) {
		return fr.renderMarkdown(name, content)
	}
	return fr.renderCode(name, content)
}

// --- markdown ---

func (fr *fileRenderer) renderMarkdown(name, content string) FileRender {
	fmTable, body := splitFrontMatter(content)

	math := &mathProtector{}
	src := math.Protect(body)

	res := &renderState{}
	md := goldmark.New(
		// extension.GFM assembled by hand, so the table extension can be
		// configured: goldmark aligns cells with style attributes, which
		// UGC strips; the align attribute survives.
		goldmark.WithExtensions(
			extension.Linkify,
			extension.Strikethrough,
			extension.TaskList,
			extension.NewTable(
				extension.WithTableCellAlignMethod(extension.TableCellAlignAttribute),
			),
			extension.Footnote,
			emoji.Emoji,
		),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
			// before footnote (101) and link (1000) inline parsers;
			// transformers: 900 avoids footnote's 999
			parser.WithInlineParsers(util.Prioritized(&sizedImageParser{}, 100)),
			parser.WithASTTransformers(util.Prioritized(&alertTransformer{}, 900)),
		),
		goldmark.WithRenderer(renderer.NewRenderer(
			// Raw HTML reaches the sanitizer instead of being omitted;
			// displayPolicy is the gate, GitHub-style.
			htmlrenderer.WithUnsafe(),
			renderer.WithNodeRenderers(
				// lower priority number wins; ours overrides the defaults
				util.Prioritized(htmlrenderer.NewRenderer(), 1000),
				util.Prioritized(&fencedRenderer{state: res, fr: fr}, 200),
				util.Prioritized(&headingRenderer{}, 200),
				util.Prioritized(&sizedImageRenderer{}, 200),
			),
		)),
	)
	var buf bytes.Buffer
	if err := md.Convert([]byte(src), &buf); err != nil {
		return FileRender{Name: name, Body: template.HTML(plainPre(content))}
	}
	safe := string(fr.policy.SanitizeBytes(buf.Bytes()))
	safe = math.Restore(safe)
	safe = wrapTables(safe)

	return FileRender{Name: name, Body: template.HTML(fmTable + safe), NeedsMath: math.Found(), NeedsMermaid: res.mermaid}
}

// wrapTables puts every table in a horizontally scrollable box, so wide
// tables (many columns, unbreakable paths) scroll instead of pushing the
// whole page wide. Runs after sanitize: the only literal "<table" left at
// this point is generated or sanitizer-approved markup — code-fence text
// is already escaped.
func wrapTables(s string) string {
	s = strings.ReplaceAll(s, "</table>", "</table></div>")
	return strings.ReplaceAll(s, "<table", `<div class="table-wrap"><table`)
}

// --- front matter (rendered as a metadata table, like GitHub) ---

// splitFrontMatter consumes a leading YAML front-matter block ("---" line to
// "---" or "..." line). It returns the table markup plus remaining source;
// when the block is absent or the top level is not a scalar-keyed mapping,
// the source passes through untouched with an empty table. Values that are
// nested collections render as compact inline values instead of a rejection.
func splitFrontMatter(src string) (string, string) {
	if !strings.HasPrefix(src, "---\n") {
		return "", src
	}
	lines := strings.Split(src, "\n")
	end := -1
	for i := 1; i < len(lines); i++ {
		if t := strings.TrimRight(lines[i], " \t\r"); t == "---" || t == "..." {
			end = i
			break
		}
	}
	if end < 0 {
		return "", src
	}
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(strings.Join(lines[1:end], "\n")), &doc); err != nil ||
		doc.Kind != yaml.DocumentNode || len(doc.Content) != 1 {
		return "", src
	}
	root := doc.Content[0]
	if root.Kind != yaml.MappingNode || len(root.Content) == 0 {
		return "", src
	}
	var b strings.Builder
	b.WriteString(`<div class="table-wrap"><table class="frontmatter"><tbody>`)
	for i := 0; i+1 < len(root.Content); i += 2 {
		k, v := root.Content[i], root.Content[i+1]
		if k.Kind != yaml.ScalarNode {
			return "", src
		}
		val := v.Value
		if v.Kind != yaml.ScalarNode {
			flowize(v)
			out, err := yaml.Marshal(v)
			if err != nil {
				return "", src
			}
			val = strings.TrimSpace(string(out))
		}
		fmt.Fprintf(&b, "<tr><th>%s</th><td>%s</td></tr>",
			stdhtml.EscapeString(k.Value), stdhtml.EscapeString(val))
	}
	b.WriteString("</tbody></table></div>\n")
	return b.String(), strings.Join(lines[end+1:], "\n")
}

// flowize restyles a node subtree as flow, so nested collections marshal to
// one inline line instead of block-form multiline.
func flowize(n *yaml.Node) {
	n.Style = yaml.FlowStyle
	for _, c := range n.Content {
		flowize(c)
	}
}

// --- headings with permalink anchors ---

// headingRenderer replaces the default heading rendering: keeps the
// parser-generated slug id and appends a hover permalink anchor.
type headingRenderer struct{}

func (h *headingRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(ast.KindHeading, h.render)
}

func (h *headingRenderer) render(w util.BufWriter, source []byte, n ast.Node, entering bool) (ast.WalkStatus, error) {
	hn := n.(*ast.Heading)
	if entering {
		fmt.Fprintf(w, "<h%d", hn.Level)
		htmlrenderer.RenderAttributes(w, n, htmlrenderer.HeadingAttributeFilter)
		w.WriteByte('>')
		return ast.WalkContinue, nil
	}
	if v, ok := n.Attribute([]byte("id")); ok {
		var idStr string
		switch id := v.(type) {
		case []byte:
			idStr = string(id)
		case string:
			idStr = id
		}
		if idStr != "" {
			fmt.Fprintf(w, `<a class="heading-anchor" href="#%s" aria-label="Link to this section">#</a>`,
				stdhtml.EscapeString(idStr))
		}
	}
	fmt.Fprintf(w, "</h%d>\n", hn.Level)
	return ast.WalkContinue, nil
}

// --- alerts (blockquote "> [!NOTE]" callouts, like GitHub) ---

var alertMarkers = map[string]string{
	"[!note]":      "note",
	"[!tip]":       "tip",
	"[!important]": "important",
	"[!warning]":   "warning",
	"[!caution]":   "caution",
}

// alertTransformer turns blockquotes whose first paragraph line is exactly an
// alert marker into classed "markdown-alert" blockquotes. The marker source
// "[!TYPE]" splits into several bracket-aware text nodes, so the first-line
// nodes are collected and removed together.
type alertTransformer struct{}

func (alertTransformer) Transform(doc *ast.Document, reader text.Reader, pc parser.Context) {
	source := reader.Source()
	_ = ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		bq, ok := n.(*ast.Blockquote)
		if !ok {
			return ast.WalkContinue, nil
		}
		p, ok := bq.FirstChild().(*ast.Paragraph)
		if !ok {
			return ast.WalkContinue, nil
		}
		// first physical line of the paragraph (marker may be the whole
		// paragraph, e.g. an empty alert body)
		var line []byte
		for c := p.FirstChild(); c != nil; c = c.NextSibling() {
			t, ok := c.(*ast.Text)
			if !ok {
				return ast.WalkContinue, nil
			}
			line = append(line, t.Segment.Value(source)...)
			if t.SoftLineBreak() {
				break
			}
		}
		typ, ok := alertMarkers[strings.ToLower(string(bytes.TrimSpace(line)))]
		if !ok {
			return ast.WalkContinue, nil
		}
		for c := p.FirstChild(); c != nil; {
			next := c.NextSibling()
			soft := false
			if t, ok := c.(*ast.Text); ok {
				soft = t.SoftLineBreak()
			}
			p.RemoveChild(p, c)
			if soft {
				break
			}
			c = next
		}
		if t, ok := p.FirstChild().(*ast.Text); ok { // trim " > " leftovers
			for t.Segment.Start < t.Segment.Stop && source[t.Segment.Start] == ' ' {
				t.Segment.Start++
			}
		}
		if !p.HasChildren() {
			bq.RemoveChild(bq, p)
		}
		bq.SetAttribute([]byte("class"), []byte("markdown-alert markdown-alert-"+typ))
		return ast.WalkContinue, nil
	})
}

// --- sized images: "![alt](url =WxH)" ---

// GitHub's explicit image sizing is not CommonMark; parse the syntax into a
// custom node. The emitted tag goes through the same sanitizer as regular
// images. (Raw <img width=height=> markup also survives the sanitizer now,
// but the markdown shorthand is what GitHub's own editor produces.)

var sizedImageMatch = regexp.MustCompile(`^!\[([^\]]*)\]\(([^\s()]+) =([0-9]*)x([0-9]*)\)`)

type sizedImageNode struct {
	ast.BaseInline
	alt, url, width, height []byte
}

var kindSizedImage = ast.NewNodeKind("SizedImage")

func (n *sizedImageNode) Kind() ast.NodeKind { return kindSizedImage }

func (n *sizedImageNode) Dump(source []byte, level int) {
	ast.DumpHelper(n, source, level, map[string]string{
		"URL": string(n.url), "Width": string(n.width), "Height": string(n.height),
	}, nil)
}

type sizedImageParser struct{}

func (sizedImageParser) Trigger() []byte { return []byte{'!'} }

func (sizedImageParser) Parse(parent ast.Node, block text.Reader, pc parser.Context) ast.Node {
	line, _ := block.PeekLine()
	m := sizedImageMatch.FindSubmatch(line)
	if m == nil || (len(m[3]) == 0 && len(m[4]) == 0) {
		return nil
	}
	block.Advance(len(m[0]))
	return &sizedImageNode{alt: m[1], url: m[2], width: m[3], height: m[4]}
}

type sizedImageRenderer struct{}

func (s *sizedImageRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(kindSizedImage, s.render)
}

func (s *sizedImageRenderer) render(w util.BufWriter, source []byte, n ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}
	ni := n.(*sizedImageNode)
	fmt.Fprintf(w, `<img src="%s" alt="%s"`,
		stdhtml.EscapeString(string(ni.url)), stdhtml.EscapeString(string(ni.alt)))
	if len(ni.width) > 0 {
		fmt.Fprintf(w, ` width="%s"`, ni.width)
	}
	if len(ni.height) > 0 {
		fmt.Fprintf(w, ` height="%s"`, ni.height)
	}
	w.WriteString(`>`)
	return ast.WalkSkipChildren, nil
}

// --- fenced code + mermaid (custom goldmark node renderer) ---

type renderState struct{ mermaid bool }

// fencedRenderer replaces goldmark's default fenced-code rendering:
// mermaid fences become <pre class="mermaid">, other languages get chroma,
// unknown ones an escaped <pre>.
type fencedRenderer struct {
	state *renderState
	fr    *fileRenderer
}

func (f *fencedRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(ast.KindFencedCodeBlock, f.render)
}

func (f *fencedRenderer) render(w util.BufWriter, source []byte, n ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}
	cb := n.(*ast.FencedCodeBlock)
	info := ""
	if cb.Info != nil {
		info = strings.ToLower(strings.TrimSpace(string(cb.Info.Segment.Value(source))))
	}
	var code strings.Builder
	lines := cb.Lines()
	for i := 0; i < lines.Len(); i++ {
		line := lines.At(i)
		code.Write(line.Value(source))
	}
	src := strings.TrimRight(code.String(), "\n")

	if info == "mermaid" {
		f.state.mermaid = true
		w.WriteString(`<pre class="mermaid">`)
		w.WriteString(stdhtml.EscapeString(src))
		w.WriteString("</pre>")
		return ast.WalkSkipChildren, nil
	}
	// Language hint is the first word of the info string (```bash matches,
	// ```bash title=x matches too); unknown hints fall back to escaped
	// preformatted text. The wrapper div lets the shared app.js attach copy
	// buttons — sanitized content carries no scripts or buttons of its own.
	lang := info
	if i := strings.IndexAny(lang, " ,"); i >= 0 {
		lang = lang[:i]
	}
	w.WriteString(`<div class="codeblock">`)
	if lexer := lexers.Get(lang); lexer != nil {
		f.fr.highlightCode(w, lexer, src, f.fr.highlight)
	} else {
		w.WriteString(plainPre(src))
	}
	w.WriteString("</div>")
	return ast.WalkSkipChildren, nil
}

// --- code files ---

func (fr *fileRenderer) renderCode(name, content string) FileRender {
	lexer := lexers.Match(name)
	if lexer == nil {
		lexer = lexers.Analyse(content)
	}
	var b bytes.Buffer
	if lexer == nil {
		return FileRender{Name: name, Body: template.HTML(plainPre(content))}
	}
	fr.highlightCode(&b, lexer, strings.TrimRight(content, "\n"), fr.numbered)
	return FileRender{Name: name, Body: template.HTML(b.String())}
}

// highlightCode tokenizes src and writes chroma markup to w. The formatter
// output is generated from escaped source, so it needs no sanitizing.
func (fr *fileRenderer) highlightCode(w io.StringWriter, lexer chroma.Lexer, src string, fm *chromahtml.Formatter) {
	var b bytes.Buffer
	it, err := chroma.Coalesce(lexer).Tokenise(nil, src)
	if err == nil {
		err = fm.Format(&b, fr.style, it)
	}
	if err != nil {
		w.WriteString(plainPre(src))
		return
	}
	w.WriteString(b.String())
}

// --- source protection (pre-goldmark math masking) ---

// mathProtector swaps MathJax-delimited spans for alphanumeric placeholders
// before goldmark parses the document (underscores in $x_i$ would otherwise
// become <em>), then restores the math — HTML-escaped and in canonical TeX
// delimiters — after sanitizing. Content inside code fences and inline code
// is left untouched.
type mathProtector struct {
	saved []string
}

var (
	mathDisplay = regexp.MustCompile(`(?s)\$\$(.+?)\$\$`)
	mathTexDisp = regexp.MustCompile(`(?s)\\\[.+?\\\]`)
	mathTexInl  = regexp.MustCompile(`\\\(.+?\\\)`)
	// Inline $...$: same line, non-empty, no space right after the opening
	// or before the closing delimiter ("$5 and $6" is money, not math).
	mathInline = regexp.MustCompile(`\$(\S(?:[^$\n]*\S)?)\$`)
)

func (m *mathProtector) Protect(src string) string {
	var out, text strings.Builder
	inFence := false
	flush := func() {
		out.WriteString(m.maskOutsideCode(text.String()))
		text.Reset()
	}
	for _, line := range strings.Split(src, "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "```") || strings.HasPrefix(t, "~~~") {
			flush()
			out.WriteString(line)
			out.WriteByte('\n')
			inFence = !inFence
			continue
		}
		if inFence {
			out.WriteString(line)
			out.WriteByte('\n')
			continue
		}
		text.WriteString(line)
		text.WriteByte('\n')
	}
	flush()
	return strings.TrimSuffix(out.String(), "\n")
}

// maskOutsideCode masks math in a text region, skipping inline code spans.
func (m *mathProtector) maskOutsideCode(s string) string {
	var out strings.Builder
	for {
		i := strings.IndexByte(s, '`')
		if i < 0 {
			out.WriteString(m.maskText(s))
			return out.String()
		}
		out.WriteString(m.maskText(s[:i]))
		end := strings.IndexByte(s[i+1:], '`')
		if end < 0 {
			out.WriteString(s[i:])
			return out.String()
		}
		span := s[i : i+1+end+1] // keep code span verbatim
		out.WriteString(span)
		s = s[i+1+end+1:]
	}
}

func (m *mathProtector) maskText(s string) string {
	for _, re := range []*regexp.Regexp{mathDisplay, mathTexDisp, mathTexInl, mathInline} {
		s = re.ReplaceAllStringFunc(s, func(match string) string {
			m.saved = append(m.saved, canonicalDelims(match))
			return "MJPH" + strconv.Itoa(len(m.saved)-1) + "XJM"
		})
	}
	return s
}

// canonicalDelims rewrites dollar-delimited spans to their TeX-delimiter
// equivalents ($$..$$ -> \[..\], $..$ -> \(..\)). MathJax is configured for
// TeX delimiters only, so dollar text the protector deliberately left alone
// (money) can never be re-detected by MathJax's own, laxer scanner.
func canonicalDelims(s string) string {
	switch {
	case strings.HasPrefix(s, "$$"):
		return `\[` + s[2:len(s)-2] + `\]`
	case strings.HasPrefix(s, "$"):
		return `\(` + s[1:len(s)-1] + `\)`
	}
	return s
}

func (m *mathProtector) Restore(s string) string {
	for i, orig := range m.saved {
		s = strings.ReplaceAll(s, "MJPH"+strconv.Itoa(i)+"XJM", stdhtml.EscapeString(orig))
	}
	return s
}

func (m *mathProtector) Found() bool { return len(m.saved) > 0 }

// --- fallback ---

func plainPre(s string) string {
	return `<pre class="fallback"><code>` + stdhtml.EscapeString(s) + `</code></pre>`
}
